# Source: https://github.com/seedstack/seed/tree/bec7366099ae9b482bc49f9b4f0551eb0ce8f2e0/security/core/src/test/resources/application.yaml
# Sourcegraph query: "context:global (lang:yaml OR lang:Java Properties) file:resources/application.(yaml|properties)"
#
# Copyright Â© 2013-2024, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging: INFO
security:
  realms: [ConfigurationRealm, X509CertificateRealm]
  cache:
    enabled: true
    manager: org.seedstack.seed.security.fixtures.TestCacheManager
  users:
    Obiwan:
      password: yodarulez
      roles: [SEED.JEDI, UNKNOWN.ROLE]
    Anakin:
      password: imsodark
      roles: [SEED.PADAWAN, OTHER.UNKNOWN.ROLE]
    R2D2:
      password: beep
      roles: [SEED.RESTBOT]
    C3P0:
      password: ewokgod
      roles: [SEED.RESTBOT.INTERPRETER]
    ThePoltergeist:
      password: bouh
      roles: [SEED.JEDI, SEED.MU.GHOST, SEED.SX.GHOST]
    nobody: foreverAlone
  roles:
    padawan: SEED.PADAWAN
    jedi: SEED.JEDI
    restbot: SEED.RESTBOT
    interpreter: SEED.RESTBOT.INTERPRETER
    ghost: SEED.{scope}.GHOST
    nothing: '*'
  permissions:
    jedi: ['lightSaber:*', 'academy:*']
    padawan: 'academy:learn'
    restbot: ['*:read', '*:update', '*:create', '*:delete' ] 
    interpreter: '*:read'
    ghost: 'site:haunt'
